version: '3'
services:
  api:
    image: zah1d/blog_img
    depends_on:
      - postgres
    ports:
      - 80:8000
    # volumes:
    #   - ./:/usr/src/app
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRATION_MINUTES=${ACCESS_TOKEN_EXPIRATION_MINUTES}
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrepass
      - POSTGRES_DB=fastapidb

    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-db: