name: CI

on: [push, pull_request]

jobs:
  build:
    environment: dailyblog_testing

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Docker engine
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build Docker images
      - name: Build Docker images
        run: docker compose -f docker-compose-dev.yml up --build -d

      # Run tests
      - name: Run Pytest
        run: docker exec -t dailyblog-dailyblog_api-1 pytest



      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dailyblog_repo

