name: CI

on: [push, pull_request]

jobs:
  build:
    environment: dailyblog_testing
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRATION_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRATION_MINUTES}}

    runs-on: ubuntu-latest

    steps:
      - name: pulling git repo
        uses: actions/checkout@v2

      # Set up Docker engine
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker images
      # - name: Build Docker images
      #   run: docker compose -f docker-compose-dev.yml up --build -d

      # Run tests
      # - name: Run Pytest
      #   run: docker exec -t dailyblog-dailyblog_api-1 pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dailyblog_repo

